version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    ports:
      - "12000:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    restart: unless-stopped
